---
title: "Cross Validated Activity"
author: "Evan Gorstein"
date: "2025-09-24"
categories: [llms, meta]
draft: true
---

When I was in college, Math Stack Exchange was an invaluable resource for me. The forum dominated  results when you googled an undergraduate math problem from an analysis or algebra class, and sifting through these questions and answers and trying to identify the one that was relevant to your problem, was itself something of a learning experience...Nowadays, we have LLMs that give you an immediate answer to your exact question and moreover, you can ask follow up questions to have steps explained at whatever level of detail you'd like. 

We should be careful to separate two groups of people in a cost-benefit analysis of this development. For a college student who would circumvent learning by using an LLMs to get immediate answers to their homework problems, this is quite a bad development. But for the enterprising student or worker, I think it's clear that LLMs are a huge W. Although there are issues (cite paper "Do LLMs make stack exchange obsolete") LLMs do a pretty incredible job answering technical questions in math and coding and provide an amazing service for independent learners in this regard. 

Descriptively, there has been a dramatic exodus from Stack Exchange as a consequence of LLMs. Just look at this graph: (caption: Stack Exchange has taken a major beating from question-answering large language models.) It's clear that Stack Exchange has taken a major beating from question-answering large language models.

But this is not the question I want to explore in this post. Rather, I'm interested in whether Stack Exchange saw a decline in its activity before ChatGPT came onto the scene? This is the question I want to answer in this post. 

Goal: For each of the subjects, provide an interval estimate of the percent difference in mean number of daily posts during the year before Chat GPT (December 2021-November 2022) versus an earlier period when I was in college (that has same balance of months to correct any seasonal effects). Visualize each interval estimate in one plot and summarize whether overall there was a decline before ChatGPT came out.

