project:
  type: website

website:
  title: "Evan Gorstein"
  site-url: https://evangorstein.github.io
  navbar:
    background: lightgrey
    search: true
    right:
      - text: "About"
        href: index.qmd
      - text: "Papers"
        href: papers.qmd
      - blog.qmd
format:
  html:
    canonical-url: true
    theme:
      - cosmo
      - brand
    css: styles.css



